name: bloc_exam
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  dio: ^5.5.0
  retrofit: ^4.1.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  auto_route: ^8.2.0
  flutter_screenutil: ^5.9.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.3
  
dev_dependencies:
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2

flutter:
  uses-material-design: true
